export const PRODUCTS = {
  carrousel: [
    {
      id: 0,
      name: "Steak do cowboy",
      category: "classicos",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 1,
      name: "Steak do cowboy",
      category: "classicos",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 2,
      name: "Steak do cowboy",
      category: "classicos",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
  open: [
    {
      id: 3,
      name: "Steak do cowboy",
      category: "entrada",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 4,
      name: "Steak do cowboy",
      category: "entrada",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 5,
      name: "Steak do cowboy",
      category: "entrada",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
  parrilla: [
    {
      id: 6,
      name: "Steak do cowboy",
      category: "parrilla",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 7,
      name: "Steak do cowboy",
      category: "parrilla",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 8,
      name: "Steak do cowboy",
      category: "parrilla",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
  hamburguers: [
    {
      id: 9,
      name: "Steak do cowboy",
      category: "hamburguer",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 10,
      name: "Steak do cowboy",
      category: "hamburguer",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 11,
      name: "Steak do cowboy",
      category: "hamburguer",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
};
