export const PRODUCTS = {
  carrousel: [
    {
      id: 0,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 1,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 2,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
  open: [
    {
      id: 1,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 1,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 2,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
  parrilla: [
    {
      id: 0,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 1,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 2,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
  hamburguers: [
    {
      id: 0,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 1,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
    {
      id: 2,
      name: "Steak do cowboy",
      duration: 42,
      price: 34,
      imageUrl: "/images/foods/menu-item-model-1.png",
      desc: "Corte extraído da parte dianteira, entre o Ancho e o Acém, extremamente macio e suculento (300g).",
      label: ["soja", "egg", "milk", "crab", "peanut"],
    },
  ],
};
